swagger: "2.0"
info:
    version: 1.0.1
    title: {{ packageJson('name') }}
    description: A sample API
    contact:
        name: Swagger API Team
        email: 'john@boats.io'
        url: https://github.com/johndcarmichael/boats/
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html

host: api.example.com
basePath: /v1
schemes:
    - https

{#
    Note that here we are including the readonly paths index,
    chase it through and you will see a usefull example of
    using nunjucks set, extends and block features to
    type less and more.
#}
paths:
    $ref: paths/index.readonly.yml
parameters:
    $ref: parameters/index.yml
definitions:
    $ref: definitions/index.yml

{{ inject([{
    toAllOperations: {
      excludePaths: ['/weather/latest'],
      includeMethods: ['get'],
      content: {
        responses: {
          '404': {
            description: 'Path & method combination not found'
          }
        }
      }
    }
  }]) }}
